services:
  server:
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - JWT_SECRET=secret-key-for-testing

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url postgres://user:password@postgres:5432/taskdb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations
volumes:
  postgres_data:
    driver: local
