services:
  server:
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
