# https://taskfile.dev

version: '3'

tasks:
  inspect:
    desc: Inspect the database schema
    cmd: atlas schema inspect --env gorm --url "env://src"
  migrate-diff:
    desc: Generate migration diff for the specified description
    aliases:
      - migd
    vars:
      DESC: '{{.CLI_ARGS}}'
    cmds:
      - |
        if [ -z "{{.DESC}}" ]; then
          echo "Please provide a description for the migration diff."
          exit 1
        fi
        if echo "{{.DESC}}" | grep -q '^[a-z0-9_-]\+$'; then
          echo "Generating migration diff with description: {{.DESC}}"
        else
          echo "Invalid description format. Only lowercase letters, numbers, underscores, and hyphens are allowed."
          exit 1
        fi
        atlas migrate diff {{.DESC}} --env gorm
    silent: true
  fuzz:
    desc: Run fuzz tests for all targets
    cmds:
      - go test -fuzz=FuzzValidateTitle ./internal/domain/task/ -fuzztime=10s
      - go test -fuzz=FuzzNewTaskWithValidation ./internal/domain/task/ -fuzztime=10s
  fuzz-validate-title:
    desc: Run fuzz test for title validation
    cmd: go test -fuzz=FuzzValidateTitle ./internal/domain/task/ -fuzztime=10s
  fuzz-new-task:
    desc: Run fuzz test for task creation
    cmd: go test -fuzz=FuzzNewTaskWithValidation ./internal/domain/task/ -fuzztime=10s
