// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for error.
type Error struct {
	// Code Error code
	Code int `json:"code"`

	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// Task defines model for task.
type Task struct {
	// Id The unique identifier for the task
	Id string `json:"id"`

	// Name The name of the task
	Name string `json:"name"`
}

// TaskCreate defines model for taskCreate.
type TaskCreate struct {
	// Name The name of the task
	Name string `json:"name"`
}

// TaskUpdate defines model for taskUpdate.
type TaskUpdate struct {
	// Name The name of the task
	Name *string `json:"name,omitempty"`
}

// TaskCreateTaskJSONRequestBody defines body for TaskCreateTask for application/json ContentType.
type TaskCreateTaskJSONRequestBody = TaskCreate

// TaskUpdateTaskJSONRequestBody defines body for TaskUpdateTask for application/json ContentType.
type TaskUpdateTaskJSONRequestBody = TaskUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all tasks
	// (GET /tasks)
	TaskGetAllTasks(c *gin.Context)
	// Create a new task
	// (POST /tasks)
	TaskCreateTask(c *gin.Context)
	// Delete a task
	// (DELETE /tasks/{taskId})
	TaskDeleteTask(c *gin.Context, taskId string)
	// Get a task
	// (GET /tasks/{taskId})
	TaskGetTask(c *gin.Context, taskId string)
	// Update a task
	// (PUT /tasks/{taskId})
	TaskUpdateTask(c *gin.Context, taskId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// TaskGetAllTasks operation middleware
func (siw *ServerInterfaceWrapper) TaskGetAllTasks(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TaskGetAllTasks(c)
}

// TaskCreateTask operation middleware
func (siw *ServerInterfaceWrapper) TaskCreateTask(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TaskCreateTask(c)
}

// TaskDeleteTask operation middleware
func (siw *ServerInterfaceWrapper) TaskDeleteTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId string

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", c.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter taskId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TaskDeleteTask(c, taskId)
}

// TaskGetTask operation middleware
func (siw *ServerInterfaceWrapper) TaskGetTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId string

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", c.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter taskId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TaskGetTask(c, taskId)
}

// TaskUpdateTask operation middleware
func (siw *ServerInterfaceWrapper) TaskUpdateTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "taskId" -------------
	var taskId string

	err = runtime.BindStyledParameterWithOptions("simple", "taskId", c.Param("taskId"), &taskId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter taskId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TaskUpdateTask(c, taskId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			details := err.Error()
			c.JSON(statusCode, Error{
				Code:    statusCode,
				Message: http.StatusText(statusCode),
				Details: &details,
			})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/tasks", wrapper.TaskGetAllTasks)
	router.POST(options.BaseURL+"/tasks", wrapper.TaskCreateTask)
	router.DELETE(options.BaseURL+"/tasks/:taskId", wrapper.TaskDeleteTask)
	router.GET(options.BaseURL+"/tasks/:taskId", wrapper.TaskGetTask)
	router.PUT(options.BaseURL+"/tasks/:taskId", wrapper.TaskUpdateTask)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXUW/bNhD+K8Rtj0KsNC5Q6M1dtsJDHwYkxR4CP7Di2WYnkSx5SuYF+u/DkXIdW5K3",
	"BHG2YXkSbZJ333387ni8h9LWzho0FKC4h1CusZZxiN5bzwPnrUNPGuPfpVXIX4Wh9NqRtgYK+JEXiziX",
	"Af4ua1chFNN8mgFtHEIB2hCu0EObgUKSugp9KzOlNA9lJaJ3sV35wCZcr1GQDL+JO01rMb8U528upm/F",
	"nQzCWBJL2xgF39wG8tqs2GuNIcjVKPbt9J4rdnPEaJuBx6+N9qiguIEu/K2lxbf19vMXLIlBMPA+p1r1",
	"UXGYjdFfGxRaoSG91OjF0npBHQF7UCMJQ2EbWeOwdZ4Rdjls7yoOxHX6/3jcmqmJfsZC/sGjJOwH/gLg",
	"juL65NRz4krm1DiwAxBtBgHLxmvaXHHiJeefUXr0s4bWu18/WV9LggJ+/vUaspSmbCnN7nytiRy0bFib",
	"pR0IgRV9hf4WvZj9MueNmnZa35u5RR/SrvOz/CxnzqxDI52GAi7O8rMLyMBJWkfUE2YjjlZI/GE+Jbud",
	"q878B6RZVV3HdXxIwVkTUsxv8jwVF0No4nbpXKXLaGDyJTCMbXWKGUNYx43fe1xCAd9NdnVs0hWxiAh2",
	"rEvv5SaRs0/KRx0onmlE1mYwzc8fheYYiFRGB7x+MrKhtfX6D1Ts9O0jKXiS07kh9FxfQzrp7cKdEKG4",
	"2ZfgzaJdZBCaupZ+AwV8QBKyqjq2OI9WgRMtsr1oM3A2jAgglYEuOzhJMdB7qzbPFveDWtPuFwLyDbY9",
	"0Z0/q+chwmNalRGSEqEpSwxh2VTVJunsBY78vVSi4/pV23+h7aQdIYXBu215P9B3m3WlbnLPn7lqU5Wt",
	"MF0kfdVfxrlO9U56WSOhDxFM/4KZXz68XgRZ0dnmkg5FLLjb67aABAEOlZ494PLwFlr0smA6ck8kx0Oy",
	"/QckNE0wT+v0oOH7Dyk3iUzIEdVmR2/lp2vTI3mNt6dUZ37yGj1L4exaw1eB/0vbjlF1u2ZE3aklf7rA",
	"m/RCeFZ5n6bv6d4yf6vvyV+m72m699D/tu95zemjOZ0kO5rWyRYbH8rXj7aUlVB4i5V1NRrqgEAGja+6",
	"t3AxmVS8bm0DFe/ydzm0i/bPAAAA///L8Efb9RIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
